export {
  AuthManager,
  AuthenticateMiddleware,
  RequireAuthMiddleware,
  RedirectIfNotAuthenticated,
  guardAuth,
  signJwt,
  verifyJwt,
  type AuthConfig,
  type AuthUser,
  type GuardType,
  type JwtConfig,
  type JwtPayload,
  type JwtTokenPair,
  type TokenConfig,
  type PasswordResetConfig,
  type EmailVerificationConfig,
  type OtpConfig,
} from './Auth.js';

export {
  Gate,
  Policy,
  GateResponse,
  AuthorizationError,
  GateMiddleware,
  GateManager,
  UserGate,
  type GateCallback,
  type BeforeCallback,
  type AfterCallback,
} from './Gate.js';
