/**
 * DeployTemplates — Template strings for deployment scaffolding.
 *
 * Used by MakeDockerCommand, MakeCiCommand, and MakeInfraCommand.
 */

export class DeployTemplates {

  // ── Dockerfile (multi-stage: base, deps, builder, production, development) ──

  static dockerfile(): string {
    return `# ── Svelar Production Dockerfile ──────────────────────────
# Multi-stage build: base → deps → builder → production / development
# Generated by: npx svelar make:docker

# ── Base ──────────────────────────────────────────────────
FROM node:20-alpine AS base
RUN apk add --no-cache dumb-init
RUN addgroup -g 1001 sveltekit && adduser -u 1001 -G sveltekit -s /bin/sh -D sveltekit

# ── Dependencies (production only) ───────────────────────
FROM base AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

# ── Builder (full install + build) ───────────────────────
FROM base AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# ── Production ───────────────────────────────────────────
FROM base AS production
WORKDIR /app

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

COPY --from=deps /app/node_modules ./node_modules
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./
COPY --from=builder /app/ecosystem.config.cjs ./
COPY --from=builder /app/src/lib/database ./src/lib/database

RUN mkdir -p storage/logs storage/public && chown -R sveltekit:sveltekit /app

USER sveltekit
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD wget -qO- http://localhost:3000/api/health || exit 1

ENTRYPOINT ["dumb-init", "--"]
CMD ["node", "build/index.js"]

# ── Development (hot-reload) ─────────────────────────────
FROM base AS development
WORKDIR /app

ENV NODE_ENV=development

COPY package*.json ./
RUN npm ci
COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
`;
  }

  // ── docker-compose.dev.yml ──

  static composeDevOverride(): string {
    return `# ── Svelar Docker Compose — Development Override ─────────
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
# Generated by: npx svelar make:docker

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "\${DEV_PORT:-5173}:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
`;
  }

  // ── docker-compose.prod.yml ──

  static composeProdOverride(image: string): string {
    return `# ── Svelar Docker Compose — Production Override ──────────
# Usage: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# Generated by: npx svelar make:docker

services:
  app:
    image: \${DOCKER_IMAGE:-${image}}:latest
    # No build — uses pre-built image from registry
`;
  }

  // ── Health endpoint ──

  static healthEndpoint(): string {
    return `import { json } from '@sveltejs/kit';

export const GET = () => json({
  status: 'ok',
  timestamp: new Date().toISOString(),
  uptime: process.uptime(),
});
`;
  }

  // ── GitHub Actions workflow ──

  static githubActionsWorkflow(image: string): string {
    return `# ── Svelar CI/CD — Build, Push & Deploy ──────────────────
# Triggered on push to main. Builds a Docker image, pushes to
# Docker Hub, then SSH-deploys to a DigitalOcean droplet.
#
# Required GitHub Secrets:
#   DOCKER_USERNAME  — Docker Hub username
#   DOCKER_TOKEN     — Docker Hub access token
#   DROPLET_HOST     — Droplet IP or hostname
#   DROPLET_USER     — SSH user on the droplet (e.g. deploy)
#   DROPLET_SSH_KEY  — Private SSH key for the deploy user
#
# Generated by: npx svelar make:ci

name: Deploy

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE: \${{ secrets.DOCKER_USERNAME }}/${image}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: \${{ secrets.DOCKER_USERNAME }}
          password: \${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          target: production
          push: true
          tags: |
            \${{ env.DOCKER_IMAGE }}:latest
            \${{ env.DOCKER_IMAGE }}:\${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to droplet
        uses: appleboy/ssh-action@v1
        with:
          host: \${{ secrets.DROPLET_HOST }}
          username: \${{ secrets.DROPLET_USER }}
          key: \${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd ~/app
            docker compose -f docker-compose.yml -f docker-compose.prod.yml pull
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
            docker image prune -f
`;
  }

  // ── Droplet setup script ──

  static setupDropletScript(): string {
    return `#!/usr/bin/env bash
# ── Svelar Droplet Setup ─────────────────────────────────
# Run this on a fresh Ubuntu 22.04+ droplet as root.
# It creates a deploy user, installs Docker, and prepares
# the project directory.
#
# Usage: ssh root@your-droplet 'bash -s' < infra/setup-droplet.sh
#
# Generated by: npx svelar make:infra

set -euo pipefail

DEPLOY_USER="\${DEPLOY_USER:-deploy}"
APP_DIR="/home/\$DEPLOY_USER/app"

echo "──────────────────────────────────────────"
echo " Svelar Droplet Setup"
echo "──────────────────────────────────────────"

# ── 1. Create deploy user ──
if ! id "\$DEPLOY_USER" &>/dev/null; then
  adduser --disabled-password --gecos "" "\$DEPLOY_USER"
  usermod -aG sudo "\$DEPLOY_USER"
  echo "\$DEPLOY_USER ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/\$DEPLOY_USER
  echo "[+] Created user: \$DEPLOY_USER"
else
  echo "[=] User \$DEPLOY_USER already exists"
fi

# ── 2. SSH keys ──
DEPLOY_HOME="/home/\$DEPLOY_USER"
mkdir -p "\$DEPLOY_HOME/.ssh"
if [ -f /root/.ssh/authorized_keys ]; then
  cp /root/.ssh/authorized_keys "\$DEPLOY_HOME/.ssh/authorized_keys"
fi
chmod 700 "\$DEPLOY_HOME/.ssh"
chmod 600 "\$DEPLOY_HOME/.ssh/authorized_keys" 2>/dev/null || true
chown -R "\$DEPLOY_USER:\$DEPLOY_USER" "\$DEPLOY_HOME/.ssh"
echo "[+] SSH keys configured"

# ── 3. Install Docker ──
if ! command -v docker &>/dev/null; then
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=\$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \$(. /etc/os-release && echo \$VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  echo "[+] Docker installed"
else
  echo "[=] Docker already installed"
fi

usermod -aG docker "\$DEPLOY_USER"

# ── 4. Project directory ──
mkdir -p "\$APP_DIR"
chown -R "\$DEPLOY_USER:\$DEPLOY_USER" "\$APP_DIR"
echo "[+] Project directory: \$APP_DIR"

# ── 5. Firewall ──
if command -v ufw &>/dev/null; then
  ufw allow OpenSSH
  ufw allow 80/tcp
  ufw allow 443/tcp
  ufw --force enable
  echo "[+] Firewall configured (SSH, HTTP, HTTPS)"
fi

echo ""
echo "──────────────────────────────────────────"
echo " Setup complete!"
echo ""
echo " Next steps:"
echo "   1. Add your SSH public key to \$DEPLOY_HOME/.ssh/authorized_keys"
echo "   2. Copy docker-compose.yml and docker-compose.prod.yml to \$APP_DIR"
echo "   3. Create .env in \$APP_DIR with production values"
echo "   4. Run: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d"
echo "──────────────────────────────────────────"
`;
  }

  // ── Droplet env example ──

  static dropletEnvExample(appName: string): string {
    return `# ── ${appName} — Production Environment ───────────────────
# Copy this file to ~/app/.env on your droplet and fill in real values.
#
# Generated by: npx svelar make:infra

# ── App ──
NODE_ENV=production
APP_URL=https://yourdomain.com
APP_KEY=  # Generate with: npx svelar key:generate
APP_PORT=3000

# ── Docker ──
DOCKER_IMAGE=${appName}

# ── Database (PostgreSQL) ──
DB_DRIVER=postgres
DB_HOST=postgres
DB_PORT=5432
DB_NAME=${appName}
DB_USER=${appName}
DB_PASSWORD=  # Use a strong password

# ── Redis ──
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=  # Use a strong password
QUEUE_DRIVER=redis

# ── Session ──
SESSION_SECRET=  # Generate a random 64-char hex string

# ── Object Storage (RustFS / S3) ──
# S3_ENDPOINT=http://rustfs:9000
# S3_ACCESS_KEY=
# S3_SECRET_KEY=
# S3_BUCKET=${appName}
# S3_REGION=us-east-1
# STORAGE_DISK=s3
`;
  }
}
