/**
 * DeployTemplates — Template strings for deployment scaffolding.
 *
 * Used by MakeDockerCommand, MakeCiCommand, and MakeInfraCommand.
 */

export class DeployTemplates {

  // ── Dockerfile (multi-stage: base, deps, builder, production, development) ──

  static dockerfile(): string {
    return `# ── Svelar Production Dockerfile ──────────────────────────
# Multi-stage build: base → deps → builder → production / development
# Generated by: npx svelar make:docker

# ── Base ──────────────────────────────────────────────────
FROM node:20-alpine AS base
RUN apk add --no-cache dumb-init
RUN addgroup -g 1001 sveltekit && adduser -u 1001 -G sveltekit -s /bin/sh -D sveltekit

# ── Dependencies (production only) ───────────────────────
FROM base AS deps
WORKDIR /app
COPY package*.json ./
COPY .svelar-local ./.svelar-local
RUN npm ci --omit=dev

# ── Builder (full install + build) ───────────────────────
FROM base AS builder
WORKDIR /app
COPY package*.json ./
COPY .svelar-local ./.svelar-local
RUN npm ci
COPY . .
RUN npm run build

# ── Production ───────────────────────────────────────────
FROM base AS production
WORKDIR /app

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

COPY --chown=sveltekit:sveltekit --from=deps /app/node_modules ./node_modules
COPY --chown=sveltekit:sveltekit --from=builder /app/build ./build
COPY --chown=sveltekit:sveltekit --from=builder /app/src ./src
COPY --chown=sveltekit:sveltekit --from=builder /app/package.json ./
COPY --chown=sveltekit:sveltekit --from=builder /app/svelar.database.json ./

RUN mkdir -p storage/logs storage/public && chown -R sveltekit:sveltekit storage

USER sveltekit
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD wget -qO- http://127.0.0.1:3000/api/health || exit 1

ENTRYPOINT ["dumb-init", "--"]
CMD ["node", "build/index.js"]

# ── Development (hot-reload) ─────────────────────────────
FROM base AS development
WORKDIR /app

ENV NODE_ENV=development

COPY package*.json ./
COPY .svelar-local ./.svelar-local
RUN npm ci
COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
`;
  }

  // ── docker-compose.dev.yml ──

  static composeDevOverride(): string {
    return `# ── Svelar Docker Compose — Development Override ─────────
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
# Generated by: npx svelar make:docker

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "\${DEV_PORT:-5173}:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
`;
  }

  // ── docker-compose.prod.yml ──

  static composeProdOverride(image: string): string {
    return `# ── Svelar Docker Compose — Production Override ──────────
# Usage: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# Generated by: npx svelar make:docker

services:
  app:
    image: \${DOCKER_IMAGE:-${image}}:latest
    # No build — uses pre-built image from registry
`;
  }

  // ── Database init scripts ──

  static postgresInit(): string {
    return `-- PostgreSQL init script
-- Runs once when the data volume is first created.
-- Add extensions, custom types, or seed data here.

-- Common extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";        -- UUID generation (uuid_generate_v4)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";         -- gen_random_uuid, encryption, hashing
CREATE EXTENSION IF NOT EXISTS "citext";           -- Case-insensitive text (emails, usernames)
CREATE EXTENSION IF NOT EXISTS "unaccent";         -- Accent-insensitive search (cafe = cafe)
CREATE EXTENSION IF NOT EXISTS "pg_trgm";          -- Fast LIKE/ILIKE, fuzzy search, similarity
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements"; -- Query performance tracking
`;
  }

  static postgresConf(): string {
    return `# PostgreSQL Configuration
# Optimized for SvelteKit/Svelar API workload with PgBouncer
# Generated by: npx svelar make:docker
#
# Default tuning: 2GB RAM / 2 vCPUs (typical $12-24/mo droplet)
# Scale values proportionally for larger instances.
# Use https://pgtune.leopard.in.ua for precise tuning.

# =============================================================================
# CONNECTIONS
# =============================================================================
# With PgBouncer handling pooling, PostgreSQL needs fewer direct connections.
# PgBouncer's max_db_connections should be less than this.
max_connections = 100
superuser_reserved_connections = 3

# =============================================================================
# MEMORY (2GB RAM baseline — scale proportionally)
# =============================================================================
# 25% of RAM for shared buffers
shared_buffers = 512MB
# Per-operation sort/hash memory (careful: multiplied by max_connections)
work_mem = 32MB
# Memory for VACUUM, CREATE INDEX, ALTER TABLE
maintenance_work_mem = 256MB
# WAL writer memory
wal_buffers = 16MB
# Estimate of OS + PostgreSQL caches (~75% of RAM)
effective_cache_size = 1536MB

# =============================================================================
# CHECKPOINT / WAL
# =============================================================================
checkpoint_completion_target = 0.9
max_wal_size = 1GB
min_wal_size = 256MB
wal_compression = on

# =============================================================================
# QUERY PLANNER
# =============================================================================
# SSD storage — lower random page cost
random_page_cost = 1.1
effective_io_concurrency = 200
default_statistics_target = 100

# =============================================================================
# PARALLEL QUERY (2 vCPUs baseline)
# =============================================================================
max_parallel_workers_per_gather = 1
max_parallel_workers = 2
max_parallel_maintenance_workers = 1
parallel_leader_participation = on

# =============================================================================
# LOGGING
# =============================================================================
log_destination = 'stderr'
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_rotation_age = 1d
log_rotation_size = 100MB

# Log slow queries (>1s)
log_min_duration_statement = 1000
log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0

log_line_prefix = '%t [%p]: user=%u,db=%d,app=%a,client=%h '

# =============================================================================
# STATISTICS / MONITORING
# =============================================================================
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.max = 10000
pg_stat_statements.track = all
pg_stat_statements.track_utility = on
pg_stat_statements.track_planning = on

track_io_timing = on
track_functions = all
track_activity_query_size = 2048

# =============================================================================
# AUTOVACUUM
# =============================================================================
autovacuum = on
autovacuum_max_workers = 3
autovacuum_naptime = 1min
autovacuum_vacuum_threshold = 50
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_threshold = 50
autovacuum_analyze_scale_factor = 0.025
autovacuum_vacuum_cost_delay = 2ms
autovacuum_vacuum_cost_limit = 1000

# =============================================================================
# LOCALE / ENCODING
# =============================================================================
lc_messages = 'en_US.utf8'
lc_monetary = 'en_US.utf8'
lc_numeric = 'en_US.utf8'
lc_time = 'en_US.utf8'

# =============================================================================
# SECURITY
# =============================================================================
password_encryption = scram-sha-256
listen_addresses = '*'
port = 5432
`;
  }

  static mysqlInit(): string {
    return `-- MySQL init script
-- Runs once when the data volume is first created.
-- Add custom tables, functions, or seed data here.

-- Ensure UTF-8 support for the default database
ALTER DATABASE IF EXISTS \`svelar\`
  CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
`;
  }

  // ── PgBouncer config ──

  static pgbouncerIni(): string {
    return `; PgBouncer configuration
; Generated by: npx svelar make:docker
; Docs: https://www.pgbouncer.org/config.html
;
; Credentials are read from DATABASE_URL env var in docker-compose.yml.
; The edoburu/pgbouncer image auto-generates the auth file from DATABASE_URL
; at startup — no static userlist.txt with plain text passwords needed.

[databases]
; * = use DATABASE_URL from environment (auto-configured by edoburu/pgbouncer image)
; To add more databases, use format: dbname = host=hostname port=port dbname=database

[pgbouncer]
; Connection settings
listen_addr = 0.0.0.0
listen_port = 6432
unix_socket_dir =

; Authentication — uses auto-generated auth file from DATABASE_URL
; Client → PgBouncer uses md5 (required: edoburu image writes plain text to userlist)
; PgBouncer → PostgreSQL uses scram-sha-256 (negotiated automatically by the server)
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt

; Pool Mode
; transaction = release connection after each transaction (best for web apps)
; session = release after session disconnects
; statement = release after each statement (not recommended with prepared statements)
pool_mode = transaction

; Pool Size Settings
; default_pool_size: connections per user/database pair
default_pool_size = 25
min_pool_size = 5
reserve_pool_size = 5
reserve_pool_timeout = 3

; Max connections
max_client_conn = 500
max_db_connections = 80
max_user_connections = 80

; Timeouts
server_connect_timeout = 15
server_idle_timeout = 300
server_lifetime = 3600
client_idle_timeout = 0
client_login_timeout = 60
query_timeout = 0
query_wait_timeout = 120

; Logging
log_connections = 1
log_disconnections = 1
log_pooler_errors = 1
stats_period = 60
verbose = 0

; TCP keepalive
tcp_keepalive = 1
tcp_keepidle = 30
tcp_keepintvl = 10
tcp_keepcnt = 3

; Server settings
server_reset_query = DISCARD ALL
server_check_query = SELECT 1
server_check_delay = 30

; Ignore startup parameters (important for Node.js drivers)
ignore_startup_parameters = extra_float_digits,application_name
`;
  }

  // ── Health endpoint ──

  static healthEndpoint(): string {
    return `import { json } from '@sveltejs/kit';

export const GET = () => json({
  status: 'ok',
  timestamp: new Date().toISOString(),
  uptime: process.uptime(),
});
`;
  }

  // ── GitHub Actions workflow ──

  static githubActionsWorkflow(): string {
    return `# ── Svelar CI/CD — Build, Push & Deploy ──────────────────
# Builds on push and PR to main. Deploys only on push.
#
# Required GitHub Secrets:
#   DOCKER_USERNAME   — Docker Hub username
#   DOCKER_TOKEN      — Docker Hub access token
#   DOCKER_IMAGE_NAME — Docker image name (e.g. myapp)
#   DROPLET_HOST      — Droplet IP or hostname
#   DROPLET_USER      — SSH user on the droplet (e.g. deploy)
#   DROPLET_SSH_KEY   — Private SSH key for the deploy user
#   DROPLET_PROJECT   — Project directory name on the droplet (e.g. myapp)
#   ENV_PROD          — Complete production .env file contents
#
# Generated by: npx svelar make:ci

name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_IMAGE: \${{ secrets.DOCKER_USERNAME }}/\${{ secrets.DOCKER_IMAGE_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: \${{ secrets.DOCKER_USERNAME }}
          password: \${{ secrets.DOCKER_TOKEN }}

      - name: Define tags
        run: |
          echo "TIMESTAMP_TAG=\$(date +%s)" >> \$GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile \\
            --target production \\
            --tag \$DOCKER_IMAGE:\$TIMESTAMP_TAG \\
            --tag \$DOCKER_IMAGE:latest

      - name: Push to Docker Hub
        if: github.event_name == 'push'
        run: |
          docker push \$DOCKER_IMAGE:\$TIMESTAMP_TAG
          docker push \$DOCKER_IMAGE:latest

      - name: Copy compose files to droplet
        if: github.event_name == 'push'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: \${{ secrets.DROPLET_HOST }}
          username: \${{ secrets.DROPLET_USER }}
          key: \${{ secrets.DROPLET_SSH_KEY }}
          source: "docker-compose.yml,docker-compose.prod.yml,docker/"
          target: \${{ secrets.DROPLET_PROJECT }}

      - name: Deploy to droplet
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1
        with:
          host: \${{ secrets.DROPLET_HOST }}
          username: \${{ secrets.DROPLET_USER }}
          key: \${{ secrets.DROPLET_SSH_KEY }}
          script: |
            echo "\${{ secrets.DOCKER_TOKEN }}" | docker login -u "\${{ secrets.DOCKER_USERNAME }}" --password-stdin
            cd \${{ secrets.DROPLET_PROJECT }}/
            echo "\${{ secrets.ENV_PROD }}" > .env
            echo "DOCKER_IMAGE=\${{ secrets.DOCKER_USERNAME }}/\${{ secrets.DOCKER_IMAGE_NAME }}" >> .env
            docker compose -f docker-compose.yml -f docker-compose.prod.yml pull
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
            docker image prune -f
`;
  }

  // ── Droplet setup script ──

  static setupDropletScript(appName: string): string {
    return `#!/usr/bin/env bash
# ── Svelar Droplet Setup ─────────────────────────────────
# Runs locally. Reads config from infra/droplet.env, SSHs into
# the droplet, creates a deploy user, adds SSH key, adds to
# docker group, creates project directory, and copies
# docker-compose.prod.yml.
#
# .env is NOT copied — it's managed by CI/CD via the ENV_PROD
# GitHub Secret (written to .env on each deploy).
#
# Usage:
#   ./infra/setup-droplet.sh
#   ./infra/setup-droplet.sh --config infra/droplet.env
#   npx svelar infra:setup  (runs this script)
#
# Generated by: npx svelar make:infra

set -euo pipefail

# ── Colors ────────────────────────────────────────────────
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
CYAN='\\033[0;36m'
NC='\\033[0m'

log()   { echo -e "\${GREEN}[+]\${NC} \$1"; }
warn()  { echo -e "\${YELLOW}[!]\${NC} \$1"; }
err()   { echo -e "\${RED}[x]\${NC} \$1" >&2; }
info()  { echo -e "\${CYAN}[>]\${NC} \$1"; }

# ── Load config (skip if env vars already set, e.g. via flags) ──
if [[ -z "\${DROPLET_IP:-}" ]]; then
  CONFIG_FILE="\${1:-infra/droplet.env}"
  if [[ "\${1:-}" == "--config" ]]; then
    CONFIG_FILE="\${2:-infra/droplet.env}"
  fi

  if [[ ! -f "\$CONFIG_FILE" ]]; then
    err "Config file not found: \$CONFIG_FILE"
    err "Copy infra/droplet.env.example to infra/droplet.env and fill in your values."
    exit 1
  fi

  # shellcheck disable=SC1090
  source "\$CONFIG_FILE"
fi

# ── Validate required vars ───────────────────────────────
REQUIRED_VARS=(DROPLET_IP DEPLOY_USER PROJECT_NAME SSH_KEY_PATH)
for var in "\${REQUIRED_VARS[@]}"; do
  if [[ -z "\${!var:-}" ]]; then
    err "Missing required variable: \$var (check \$CONFIG_FILE)"
    exit 1
  fi
done

SSH_PUB_KEY="\${SSH_KEY_PATH}.pub"
DEPLOY_USER_PASSWORD="\${DEPLOY_USER_PASSWORD:-}"

# Compose files to copy to the server
COMPOSE_BASE="docker-compose.yml"
COMPOSE_PROD="\${COMPOSE_FILE:-docker-compose.prod.yml}"

if [[ ! -f "\$SSH_KEY_PATH" ]]; then
  err "SSH private key not found: \$SSH_KEY_PATH"
  exit 1
fi
if [[ ! -f "\$SSH_PUB_KEY" ]]; then
  err "SSH public key not found: \$SSH_PUB_KEY"
  exit 1
fi
if [[ ! -f "\$COMPOSE_BASE" ]]; then
  err "Compose file not found: \$COMPOSE_BASE"
  exit 1
fi
if [[ ! -f "\$COMPOSE_PROD" ]]; then
  err "Compose file not found: \$COMPOSE_PROD"
  exit 1
fi

# Validate paths don't contain spaces (word-splitting would break SSH commands)
if [[ "\$SSH_KEY_PATH" == *" "* ]]; then
  err "SSH_KEY_PATH must not contain spaces: \$SSH_KEY_PATH"
  exit 1
fi

SSH_ROOT="ssh -o StrictHostKeyChecking=accept-new -i \$SSH_KEY_PATH root@\$DROPLET_IP"
SSH_USER="ssh -o StrictHostKeyChecking=accept-new -i \$SSH_KEY_PATH \$DEPLOY_USER@\$DROPLET_IP"
PUB_KEY_CONTENT=\$(cat "\$SSH_PUB_KEY")

echo ""
echo -e "\${CYAN}======================================================\${NC}"
echo -e "\${CYAN}   Svelar Droplet Setup\${NC}"
echo -e "\${CYAN}======================================================\${NC}"
echo ""
info "Droplet IP:    \$DROPLET_IP"
info "Deploy user:   \$DEPLOY_USER"
info "Project:       \$PROJECT_NAME"
info "SSH key:       \$SSH_KEY_PATH"
info "Compose files: \$COMPOSE_BASE + \$COMPOSE_PROD"
echo ""

read -rp "Proceed with setup? (y/N) " confirm
if [[ "\$confirm" != "y" && "\$confirm" != "Y" ]]; then
  warn "Aborted."
  exit 0
fi

# ── Step 1: Create non-root user ─────────────────────────
info "Step 1/6 — Creating user '\$DEPLOY_USER'..."

\$SSH_ROOT bash -s <<REMOTE_SCRIPT
  set -euo pipefail

  if id "\$DEPLOY_USER" &>/dev/null; then
    echo "User \$DEPLOY_USER already exists, skipping creation."
  else
    useradd -m -s /bin/bash "\$DEPLOY_USER"
    echo "User \$DEPLOY_USER created."
  fi

  # Add to sudo group
  usermod -aG sudo "\$DEPLOY_USER"

  # Set password if provided (optional, for emergency console access)
  if [[ -n "\${DEPLOY_USER_PASSWORD}" ]]; then
    echo "\$DEPLOY_USER:\${DEPLOY_USER_PASSWORD}" | chpasswd
    echo "Password set for \$DEPLOY_USER."
  fi

  # Allow passwordless sudo for Docker commands only (principle of least privilege)
  echo "\$DEPLOY_USER ALL=(ALL) NOPASSWD:/usr/bin/docker,/usr/bin/docker-compose,/usr/local/bin/docker-compose" > /etc/sudoers.d/\$DEPLOY_USER
  chmod 440 /etc/sudoers.d/\$DEPLOY_USER
REMOTE_SCRIPT

log "User '\$DEPLOY_USER' created with sudo."

# ── Step 2: Copy SSH key to new user ─────────────────────
info "Step 2/6 — Copying SSH key to '\$DEPLOY_USER'..."

\$SSH_ROOT bash -s <<REMOTE_SCRIPT
  set -euo pipefail

  USER_HOME=\\$(eval echo ~\$DEPLOY_USER)
  mkdir -p \\$USER_HOME/.ssh
  chmod 700 \\$USER_HOME/.ssh

  # Add key if not already present
  AUTHORIZED=\\$USER_HOME/.ssh/authorized_keys
  touch \\$AUTHORIZED
  if ! grep -qF "\$PUB_KEY_CONTENT" \\$AUTHORIZED; then
    echo "\$PUB_KEY_CONTENT" >> \\$AUTHORIZED
    echo "SSH key added."
  else
    echo "SSH key already present."
  fi

  chmod 600 \\$AUTHORIZED
  chown -R \$DEPLOY_USER:\$DEPLOY_USER \\$USER_HOME/.ssh
REMOTE_SCRIPT

log "SSH key configured."

# ── Step 3: Install Docker (if not already installed) ────
info "Step 3/6 — Checking Docker..."

\$SSH_ROOT bash -s <<REMOTE_SCRIPT
  set -euo pipefail

  if command -v docker &>/dev/null; then
    echo "Docker already installed: \\$(docker --version)"
  else
    echo "Docker not found. Installing..."
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=\\$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \\$(. /etc/os-release && echo \\$VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    echo "Docker installed: \\$(docker --version)"
  fi

  usermod -aG docker \$DEPLOY_USER
  echo "\$DEPLOY_USER added to docker group."
REMOTE_SCRIPT

log "Docker ready, user added to docker group."

# ── Step 4: Create project directory ─────────────────────
info "Step 4/6 — Creating project directory..."

\$SSH_ROOT bash -s <<REMOTE_SCRIPT
  set -euo pipefail

  USER_HOME=\\$(eval echo ~\$DEPLOY_USER)
  PROJECT_DIR=\\$USER_HOME/\$PROJECT_NAME

  mkdir -p \\$PROJECT_DIR
  chown -R \$DEPLOY_USER:\$DEPLOY_USER \\$PROJECT_DIR
  echo "Project directory: \\$PROJECT_DIR"
REMOTE_SCRIPT

log "Project directory created."

# ── Step 5: Copy compose files ───────────────────────────
info "Step 5/6 — Copying compose files to server..."

REMOTE_DIR="/home/\$DEPLOY_USER/\$PROJECT_NAME"

scp -o StrictHostKeyChecking=accept-new -i "\$SSH_KEY_PATH" \\
  "\$COMPOSE_BASE" "\$DEPLOY_USER@\$DROPLET_IP:\$REMOTE_DIR/docker-compose.yml"

scp -o StrictHostKeyChecking=accept-new -i "\$SSH_KEY_PATH" \\
  "\$COMPOSE_PROD" "\$DEPLOY_USER@\$DROPLET_IP:\$REMOTE_DIR/docker-compose.prod.yml"

# Copy docker config directory (postgres, pgbouncer configs)
if [[ -d "docker" ]]; then
  scp -o StrictHostKeyChecking=accept-new -i "\$SSH_KEY_PATH" -r \\
    docker "\$DEPLOY_USER@\$DROPLET_IP:\$REMOTE_DIR/"
  log "Docker config files copied (docker/ directory)."
fi

log "Compose files copied (.env is managed by CI/CD via ENV_PROD secret)."

# ── Step 6: Configure firewall ───────────────────────────
info "Step 6/6 — Configuring firewall..."

\$SSH_ROOT bash -s <<REMOTE_SCRIPT
  set -euo pipefail

  if command -v ufw &>/dev/null; then
    ufw allow OpenSSH
    ufw allow 80/tcp
    ufw allow 443/tcp
    ufw --force enable
    echo "UFW configured (SSH, HTTP, HTTPS)."
  else
    echo "UFW not found, skipping firewall setup."
  fi
REMOTE_SCRIPT

log "Firewall configured."

# ── Verify ───────────────────────────────────────────────
echo ""
info "Verifying setup..."

\$SSH_USER bash -s <<REMOTE_SCRIPT
  echo "  User: \\$(whoami)"
  echo "  Docker: \\$(docker --version 2>/dev/null || echo 'not available yet — relog needed')"
  echo "  Project dir: \\$(ls -la ~/\$PROJECT_NAME/)"
REMOTE_SCRIPT

echo ""
echo -e "\${GREEN}======================================================\${NC}"
echo -e "\${GREEN}   Setup Complete!\${NC}"
echo -e "\${GREEN}======================================================\${NC}"
echo ""
log "Connect with: ssh -i \$SSH_KEY_PATH \$DEPLOY_USER@\$DROPLET_IP"
echo ""
info "Next steps:"
echo "  1. Add these GitHub Secrets for CI/CD:"
echo "     DOCKER_USERNAME  — Docker Hub username"
echo "     DOCKER_TOKEN     — Docker Hub access token"
echo "     DROPLET_HOST     — \$DROPLET_IP"
echo "     DROPLET_USER     — \$DEPLOY_USER"
echo "     DROPLET_SSH_KEY  — contents of \$SSH_KEY_PATH"
echo "     ENV_PROD         — complete production .env contents"
echo ""
echo "  2. Push to main — GitHub Actions builds, pushes, and deploys:"
echo "     git push origin main"
echo ""
`;
  }

  // ── Droplet env config (infra settings, not app env) ──

  static dropletEnvExample(appName: string): string {
    return `# ── Droplet Setup Configuration ────────────────────────────
# Copy this file to infra/droplet.env and fill in your values:
#   cp infra/droplet.env.example infra/droplet.env
#
# Then run: npx svelar infra:setup
#           (or: ./infra/setup-droplet.sh)
#
# Generated by: npx svelar make:infra

# ── Required ──────────────────────────────────────────────

# IP of the DigitalOcean droplet (from the DO dashboard)
DROPLET_IP=

# Non-root user to create for deployments
DEPLOY_USER=deploy

# Project name (used as directory name on the server: ~/PROJECT_NAME)
PROJECT_NAME=${appName}

# Path to your SSH private key (public key = this path + .pub)
SSH_KEY_PATH=~/.ssh/id_ed25519

# ── Optional ──────────────────────────────────────────────

# Docker compose file to copy to the server
COMPOSE_FILE=docker-compose.prod.yml

# Password for the deploy user (optional, for emergency console access)
DEPLOY_USER_PASSWORD=
`;
  }
}
