/**
 * make:broadcasting — Scaffold broadcasting routes and client setup
 *
 * Creates the Pusher/Soketi channel auth endpoint, the SSE streaming
 * endpoint, and an example client-side initialization file.
 */

import { Command } from '../Command.js';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

export class MakeBroadcastingCommand extends Command {
  name = 'make:broadcasting';
  description = 'Scaffold broadcasting routes (Pusher auth, SSE stream, client init)';
  arguments = [];
  flags = [
    { name: 'sse', description: 'Only scaffold SSE routes (no Pusher auth)', type: 'boolean' as const },
    { name: 'pusher', description: 'Only scaffold Pusher/Soketi routes', type: 'boolean' as const },
    { name: 'force', alias: 'f', description: 'Overwrite existing files', type: 'boolean' as const },
  ];

  async handle(args: string[], flags: Record<string, any>): Promise<void> {
    const cwd = process.cwd();
    const force = flags.force ?? false;
    const sseOnly = flags.sse ?? false;
    const pusherOnly = flags.pusher ?? false;
    const both = !sseOnly && !pusherOnly;

    const files: Array<{ path: string; content: string; label: string; dirs: string[] }> = [];

    // ── Pusher/Soketi auth endpoint ──
    if (both || pusherOnly) {
      files.push({
        path: join(cwd, 'src/routes/api/broadcasting/auth/+server.ts'),
        content: this.pusherAuthRoute(),
        label: 'src/routes/api/broadcasting/auth/+server.ts',
        dirs: [join(cwd, 'src/routes/api/broadcasting/auth')],
      });
    }

    // ── SSE streaming endpoint ──
    if (both || sseOnly) {
      files.push({
        path: join(cwd, 'src/routes/api/broadcasting/[channel]/+server.ts'),
        content: this.sseRoute(),
        label: 'src/routes/api/broadcasting/[channel]/+server.ts',
        dirs: [join(cwd, 'src/routes/api/broadcasting/[channel]')],
      });
    }

    // ── Client-side initialization ──
    files.push({
      path: join(cwd, 'src/lib/broadcasting.ts'),
      content: both || pusherOnly ? this.clientPusher() : this.clientSSE(),
      label: 'src/lib/broadcasting.ts',
      dirs: [join(cwd, 'src/lib')],
    });

    // ── Config file (if missing) ──
    const configPath = join(cwd, 'config/broadcasting.ts');
    if (!existsSync(configPath)) {
      files.push({
        path: configPath,
        content: this.configTemplate(),
        label: 'config/broadcasting.ts',
        dirs: [join(cwd, 'config')],
      });
    }

    let created = 0;
    let skipped = 0;

    for (const file of files) {
      if (existsSync(file.path) && !force) {
        this.warn(`${file.label} already exists (use --force to overwrite)`);
        skipped++;
        continue;
      }
      for (const dir of file.dirs) {
        mkdirSync(dir, { recursive: true });
      }
      writeFileSync(file.path, file.content);
      this.success(`Created ${file.label}`);
      created++;
    }

    this.newLine();
    if (created > 0) {
      this.info(`${created} file(s) created${skipped > 0 ? `, ${skipped} skipped` : ''}`);
    } else {
      this.info('No files created (all exist already)');
    }

    this.newLine();
    this.info('Next steps:');

    if (both || pusherOnly) {
      this.log('  1. Install pusher-js: npm install pusher-js');
      this.log('  2. Add Pusher env vars to .env:');
      this.log('       BROADCAST_DRIVER=pusher');
      this.log('       PUSHER_KEY=svelar-key');
      this.log('       PUSHER_SECRET=svelar-secret');
      this.log('       PUSHER_APP_ID=svelar-app');
      this.log('       PUSHER_HOST=localhost    # or "soketi" in Docker');
      this.log('       PUSHER_PORT=6001');
      this.log('  3. Import broadcasting in your root layout:');
      this.log("       import '$lib/broadcasting';");
    } else {
      this.log("  1. Import broadcasting in your root layout:");
      this.log("       import '$lib/broadcasting';");
    }

    this.log('  4. Register channel authorizations in src/app.ts');
    this.log("  5. Run 'npx svelar make:docker' for Soketi in Docker Compose");
  }

  // ── Templates ──────────────────────────────────────────────

  private pusherAuthRoute(): string {
    return `/**
 * Pusher/Soketi Channel Authorization Endpoint
 *
 * This route authenticates channel subscriptions from pusher-js.
 * When a client subscribes to a private- or presence- channel,
 * pusher-js sends a POST here with socket_id and channel_name.
 *
 * Generated by: npx svelar make:broadcasting
 */

import type { RequestHandler } from '@sveltejs/kit';
import { Broadcast } from 'svelar/broadcasting';

export const POST: RequestHandler = async ({ request, locals }) => {
  // Require authenticated user
  const user = (locals as any).user;
  if (!user) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), {
      status: 401,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  // Parse the request (pusher-js sends form-encoded data)
  const form = await request.formData();
  const socketId = form.get('socket_id') as string;
  const channelName = form.get('channel_name') as string;

  if (!socketId || !channelName) {
    return new Response(JSON.stringify({ error: 'Missing socket_id or channel_name' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  // Authenticate the channel subscription
  const auth = await Broadcast.authenticatePusher(channelName, socketId, user);

  if (!auth) {
    return new Response(JSON.stringify({ error: 'Forbidden' }), {
      status: 403,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  return new Response(JSON.stringify(auth), {
    headers: { 'Content-Type': 'application/json' },
  });
};
`;
  }

  private sseRoute(): string {
    return `/**
 * SSE Broadcasting Stream Endpoint
 *
 * This route creates a Server-Sent Events stream for real-time
 * event broadcasting without WebSockets. Handles public, private,
 * and presence channels.
 *
 * Client usage:
 *   const events = new EventSource('/api/broadcasting/private-orders.123');
 *   events.addEventListener('OrderShipped', (e) => console.log(JSON.parse(e.data)));
 *
 * Generated by: npx svelar make:broadcasting
 */

import type { RequestHandler } from '@sveltejs/kit';
import { Broadcast } from 'svelar/broadcasting';

export const GET: RequestHandler = async ({ params, locals }) => {
  const channelName = params.channel;
  if (!channelName) {
    return new Response('Channel name required', { status: 400 });
  }

  const user = (locals as any).user;

  // Check authorization for private/presence channels
  if (channelName.startsWith('private-') || channelName.startsWith('presence-')) {
    if (!user) {
      return new Response('Unauthorized', { status: 401 });
    }

    const auth = await Broadcast.authorize(channelName, user);
    if (auth === false) {
      return new Response('Forbidden', { status: 403 });
    }

    // For presence channels, pass user info for member tracking
    const userInfo = typeof auth === 'object' ? auth : undefined;
    return Broadcast.subscribe(channelName, user.id, userInfo);
  }

  // Public channel — no auth needed
  return Broadcast.subscribe(channelName, user?.id);
};
`;
  }

  private clientPusher(): string {
    return `/**
 * Broadcasting Client Initialization
 *
 * Import this file in your root +layout.svelte to set up
 * real-time broadcasting via Pusher/Soketi.
 *
 * Generated by: npx svelar make:broadcasting
 */

import { usePusher } from 'svelar/broadcasting/client';

// Initialize the Pusher connection.
// These values should match your .env / docker-compose config.
export const echo = usePusher({
  key: import.meta.env.VITE_PUSHER_KEY ?? 'svelar-key',
  wsHost: import.meta.env.VITE_PUSHER_HOST ?? 'localhost',
  wsPort: Number(import.meta.env.VITE_PUSHER_PORT ?? 6001),
  forceTLS: false,
  authEndpoint: '/api/broadcasting/auth',
  enabledTransports: ['ws', 'wss'],
});

// Re-export channel helpers for convenience
export { useChannel, usePresenceChannel, leaveChannel } from 'svelar/broadcasting/client';
`;
  }

  private clientSSE(): string {
    return `/**
 * Broadcasting Client Initialization (SSE)
 *
 * Import this file in your root +layout.svelte to set up
 * real-time broadcasting via Server-Sent Events.
 *
 * Generated by: npx svelar make:broadcasting
 */

// Re-export the SSE helper for convenience
export { useSSE } from 'svelar/broadcasting/client';
`;
  }

  private configTemplate(): string {
    return `import { env } from 'svelar/config';

export default {
  default: env('BROADCAST_DRIVER', 'pusher'),

  drivers: {
    pusher: {
      driver: 'pusher' as const,
      key: env('PUSHER_KEY', 'svelar-key'),
      secret: env('PUSHER_SECRET', 'svelar-secret'),
      appId: env('PUSHER_APP_ID', 'svelar-app'),
      cluster: env('PUSHER_CLUSTER', 'mt1'),
      host: env('PUSHER_HOST', 'localhost'),
      port: env<number>('PUSHER_PORT', 6001),
      useTLS: env<boolean>('PUSHER_TLS', false),
    },

    sse: {
      driver: 'sse' as const,
    },

    log: {
      driver: 'log' as const,
    },
  },
};
`;
  }
}
