import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'orm/index': 'src/orm/index.ts',
    'hooks/index': 'src/hooks/index.ts',
    'cli/index': 'src/cli/index.ts',
    'cli/bin': 'src/cli/bin.ts',
    'container/index': 'src/container/index.ts',
    'middleware/index': 'src/middleware/index.ts',
    'routing/index': 'src/routing/index.ts',
    'database/index': 'src/database/index.ts',
    'validation/index': 'src/validation/index.ts',
    'auth/index': 'src/auth/index.ts',
    'hashing/index': 'src/hashing/index.ts',
    'session/index': 'src/session/index.ts',
    'errors/index': 'src/errors/index.ts',
    'pagination/index': 'src/pagination/index.ts',
    'events/index': 'src/events/index.ts',
    'logging/index': 'src/logging/index.ts',
    'storage/index': 'src/storage/index.ts',
    'cache/index': 'src/cache/index.ts',
    'queue/index': 'src/queue/index.ts',
    'mail/index': 'src/mail/index.ts',
    'notifications/index': 'src/notifications/index.ts',
    'broadcasting/index': 'src/broadcasting/index.ts',
    'broadcasting/client': 'src/broadcasting/client.ts',
    'config/index': 'src/config/index.ts',
    'services/index': 'src/services/index.ts',
    'actions/index': 'src/actions/index.ts',
    'repositories/index': 'src/repositories/index.ts',
    'plugins/index': 'src/plugins/index.ts',
    'scheduler/index': 'src/scheduler/index.ts',
    'permissions/index': 'src/permissions/index.ts',
    'http/index': 'src/http/index.ts',
    'i18n/index': 'src/i18n/index.ts',
    'forms/index': 'src/forms/index.ts',
    'pdf/index': 'src/pdf/index.ts',
    'pdf/GeneratePdfJob': 'src/pdf/GeneratePdfJob.ts',
    'dashboard/index': 'src/dashboard/index.ts',
    'audit/index': 'src/audit/index.ts',
    'api-keys/index': 'src/api-keys/index.ts',
    'webhooks/index': 'src/webhooks/index.ts',
    'teams/index': 'src/teams/index.ts',
    'email-templates/index': 'src/email-templates/index.ts',
    'uploads/index': 'src/uploads/index.ts',
    'queue/JobMonitor': 'src/queue/JobMonitor.ts',
    'scheduler/ScheduleMonitor': 'src/scheduler/ScheduleMonitor.ts',
    'logging/LogViewer': 'src/logging/LogViewer.ts',
    'support/date': 'src/support/date.ts',
    'plugins/PluginRegistry': 'src/plugins/PluginRegistry.ts',
    'plugins/PluginPublisher': 'src/plugins/PluginPublisher.ts',
    'plugins/PluginInstaller': 'src/plugins/PluginInstaller.ts',
  },
  format: ['esm'],
  dts: false,
  clean: true,
  sourcemap: true,
  target: 'node20',
  splitting: false,
  external: [
    '@sveltejs/kit',
    'date-fns',
    'date-fns/locale',
    'sveltekit-superforms',
    'sveltekit-superforms/adapters',
    'svelte',
    'better-sqlite3',
    'mysql2',
    'postgres',
    'drizzle-orm',
    'drizzle-orm/better-sqlite3',
    'drizzle-orm/mysql2',
    'drizzle-orm/postgres-js',
    'bcrypt',
    'argon2',
    'nodemailer',
    'ioredis',
    'node:sqlite',
    'node:crypto',
    'node:fs',
    'node:path',
    'node:url',
    'node:module',
  ],
});
